### ISSUE TITLE
MsgPack code

### ISSUE THREAD

**Issue by darkl** [IOT-DSA/sdk-dslink-dotnet#1]
Hi,

I've seen the work you've done with my implementation of Newtonsoft.Msgpack, the fact you got rid of MsgPack.Cli dependency. In fact, I wanted a lot of time to try to get rid of MsgPack.Cli, mostly for performance reasons. (Newtonsoft.Msgpack is much slower than both Newtonsoft.Json and MsgPack.Cli)

I wanted to ask you if you've tested your code and if it is in fact much faster?
If so, I'd be happy to merge your changes in to Newtonsoft.Msgpack. I'm not sure how does it work regarding licenses - do I need to change something in Newtonsoft.Msgpack in order to be able to merge your changes? Maybe you can simply open a pull request with your changes?

Thanks for your coperation
Elad

**Comment by darkl** [comment]
Oh sorry, the code actually does use MsgPack.Cli. I've accidentally thought it doesn't since I saw your own MsgPack implementation.

**Comment by logangorence** [comment]
@darkl Yeah, I was planning on using my own implementation, but I saw your integration with Newtonsoft, so I tried it out, and I love it. Plus, my MsgPack implementation was a bit buggy.
