### ISSUE TITLE
Need a way to explicitly set timestamp in Value object

### ISSUE THREAD

**Issue by mbreissi** [IOT-DSA/sdk-dslink-dotnet#27]
Currently, the SDK always sets the timestamp associated with a value object to be the system time at the time of a value update.  However, in real world links where we are receiving data from devices, we actually want to use the timestamp from telemetry coming from the device (i.e., the measurement time) rather than the time we set the value/publish in the link (i.e., the receipt time).  This is critically important in industrial IoT scenarios.  The Java SDK allows us to do it.  Dotnet should as well.

**Comment by logangorence** [comment]
@mbreissi I just committed the change 3d2f7eb, which adds a SetLastUpdated method in Value.cs. Please let me know if there are any other changes necessary to this.

**Comment by logangorence** [comment]
What is the process of doing this with the Java SDK? I looked at the implementation of the equivalent method, but I'm unsure of the usage of it. The way this SDK handles Value might need to be changed in order to properly send out the set timestamp.

**Comment by mbreissi** [comment]
In the Java SDK, you can set the timestamp on the Value object first in the Value object constructor.  Then you can call node.setValue(value) to trigger the actual publish.  It appears in the C# code that value.set() always overrides whatever is set in the lastUpdated field *and* that triggers the actual publish.  I think to properly fix, the Value::set method is going to need to have an additional optional parameter that is the timestamp.  If it's present, then use it.  If not, then do what it does now.

**Comment by mbreissi** [comment]
Here is a suggested implementation that doesn't break existing code but provides the needed functionality.

[Value.cs.zip](https://github.com/IOT-DSA/sdk-dslink-dotnet/files/2318044/Value.cs.zip)

**Comment by mbreissi** [comment]
Here is a suggested fix that does not break existing code.  It also includes the fix for issue #50 .
[Value.cs.zip](https://github.com/IOT-DSA/sdk-dslink-dotnet/files/2318053/Value.cs.zip)
