### ISSUE TITLE
Node::InitializeClass() call to ResetNode() always occurs

### ISSUE THREAD

**Issue by mbreissi** [IOT-DSA/sdk-dslink-dotnet#28]
ResetNode() node always occurs preventing nodes from being properly created.  For example, the following code:

```
                Responder.SuperRoot.CreateChild(name, LinkConstants.NodeProfile.PI_LINK_CONNECTION.ToString())
                    .SetDisplayName(name)
                    .SetConfig(LinkConstants.Connection.CONFIG_HOST, new Value(host))
                    .SetConfig(LinkConstants.Connection.CONFIG_PORT, new Value(port))
                    .BuildNode();
```
would not contain the appropriate configs after being called due to ResetNode() getting called in InitializeClass(), which is called from NodeFactory::BuildNode().  Basically, the call to ResetNode() prevents NodeFactory from working correctly.  There is a guard around ResetNode(), but I suspect it is not functioning as intended.

**Comment by logangorence** [comment]
Commit f7dea22 should change the workflow a bit. InitializeClass is now called before CreateNode ever completes, so any changes you make after that will be applied to the Node. Again, let me know if there are any changes that should be made.
