### ISSUE TITLE
InvokeResponse class needs a way to signify an error

### ISSUE THREAD

**Issue by mbreissi** [IOT-DSA/sdk-dslink-dotnet#34]
Currently, "system"/"protocol" errors such as "PermissionDenied" cannot be represented in the InvokeResponse class.  Null return tables show up as empty tables.  Suggest addition of some form of error member for the class that can be checked.

**Comment by venerablebed** [comment]
@mbreissi Please have a look at the develop branch.  We've added your suggested changes, tested, and validated.  Please let us know if this enhancement meets your needs.
