### ISSUE TITLE
DSLinkRequester::ProcessUpdateObject fails

### ISSUE THREAD

**Issue by mbreissi** [IOT-DSA/sdk-dslink-dotnet#35]
ProcessUpdateObject assumes that the count/sum/min/max elements will always be present in a subscription update message.  They are not.  Currently an exception is thrown causing a link that creates subscriptions to fail.

Need guards in the method to protect against updates without count/min/max/sum in the payload.

Additionally, currently the min/max/sum are fixed as type "int".  They are actually "Number" according to the spec and should be coerced to double (at a minimum) as the source node type may be a floating point/double number.

A functioning version is as follows (though there may be more efficient methods of implementation):

```
        private void ProcessUpdateObject(dynamic update)
        {
            JObject objectUpdate = update;
            int sid = objectUpdate["sid"].Value<int>();
            JToken value = objectUpdate["value"];
            string ts = objectUpdate["ts"].Value<string>();

			JToken placeHolder;
			int count = 1;
			double sum = 0;
			double min = 0;
			double max = 0;
			if (objectUpdate.TryGetValue("count", out placeHolder))
			{
				count = placeHolder.Value<int>();
			}
			if (objectUpdate.TryGetValue("sum", out placeHolder))
			{
				sum = placeHolder.Value<double>();
			}
			if (objectUpdate.TryGetValue("min", out placeHolder))
			{
				min = placeHolder.Value<double>();
			}
			if (objectUpdate.TryGetValue("max", out placeHolder))
			{
				max = placeHolder.Value<double>();
			}

			RemoteSubscriptionManager.InvokeSubscriptionUpdate(sid, new SubscriptionUpdate(sid, value, ts, count, sum, min, max));
        }
```

Note: this requires also changing SubscriptionUpdate members sum/min/max to be of type double.

**Comment by venerablebed** [comment]
@mbreissi Please have a look at the develop branch.  We've implemented a fix for this issue, tested, and validated.  Please let us know if this change addresses this issue.
