### ISSUE TITLE
Reconnect logic fails on WebSocketConnector::Connect()

### ISSUE THREAD

**Issue by mbreissi** [IOT-DSA/sdk-dslink-dotnet#41]
Once issue #40 is fixed, the reconnect logic takes effect.  However, it does not work.  The WebSocketConnect::Connect() method attempts to call ClientWebSocket::ConnectAsync() on the same ClientWebSocket instance (WebSocketConnector member) that failed.  That member, however, was disposed when the connection is terminated leaving it in an invalid state.

**Comment by venerablebed** [comment]
@mbreissi Please have a look at the develop branch.  We've implemented a fix for this issue, tested, and validated.  Please let us know if this change addresses this issue.
