### ISSUE TITLE
Node class needs a ClearChildren() method

### ISSUE THREAD

**Issue by mbreissi** [IOT-DSA/sdk-dslink-dotnet#46]
Java SDK has this method.  It is useful for removing all the child nodes from a Node easily.  It is used in links  when the existence of their children is dependent on the state of an external system and the set of children must be "refreshed" upon occasion (either through an action or timed event).  Sometimes it is easier to simply remove all the children and recreate them with the fresh list than attempting to merge them.

**Comment by venerablebed** [comment]
@mbreissi Please have a look at the develop branch.  We've added your suggested changes, tested, and validated.  Please let us know if this enhancement meets your needs.
