### ISSUE TITLE
Connector should not use System.Net.WebSocket methods

### ISSUE THREAD

**Issue by mbreissi** [IOT-DSA/sdk-dslink-dotnet#48]
Currently, the Write methods catches WebSocketException, breaking the protocol independence of the Connector class.  It appears that the catch block is unnecessary as web socket exceptions are caught in the descendant class (WebSocketBaseConnector), making this dependence unnecessary.  Consider either: (1) removing the try/catch block; or (2) catching a more generic Exception that is not protocol specific.

**Comment by logangorence** [comment]
This is fixed via #49.
