### ISSUE TITLE
Need to log to file with configurable location

### ISSUE THREAD

**Issue by mbreissi** [IOT-DSA/sdk-dslink-dotnet#54]
The current SDK only allows logging to the console.  Need to add a logger implementation that logs to a file at a configurable location optionally specified on the command line with the "f|log-file=" flag.  Possible loggers to use are NLog or Log4Net.

**Comment by venerablebed** [comment]
@mbreissi Please have a look at the develop branch.  We've added your suggested changes, tested, and validated.  Please let us know if this enhancement meets your needs.
