### ISSUE TITLE
Missing key options on the command line argument processor for life cycle manager compatibility

### ISSUE THREAD

**Issue by mbreissi** [IOT-DSA/sdk-dslink-dotnet#55]
Complete set supported by the Java SDK:

--broker, -b
--token, -t
--nodes, -n
--key, -k 
--log, -l 
--log-file, -f 
--dslink-json, -d 
--name 
--help, -h 

Currently only broker/token/log are supported.

**Comment by venerablebed** [comment]
@mbreissi Please have a look at the develop branch.  We've added your suggested changes, tested, and validated.  Please let us know if this enhancement meets your needs.
